
apiVersion: v1
kind: Service
metadata:
  name: greeting-svc
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: greeting-app
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting-app
    spec:
      containers:
      - name: greeting
        image: vcrepin/greeting:0.1.7
        ports:
          - containerPort: 8081
