apiVersion: v1
kind: Service
metadata:
  name: extensible-service-proxy-greeting-svc
  namespace: lacapitaletemplate
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
    protocol: TCP
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: extensible-service-proxy-greeting
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: extensible-service-proxy-greeting
  namespace: lacapitaletemplate
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: extensible-service-proxy-greeting
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config-oauth
        - name: nginx-ssl
          secret:
            secretName: nginx-ssl
        - name: service-account-creds
          secret:
            secretName: service-account-creds
      containers:
      - name: greeting
        image: vcrepin/greeting:0.1.7
        ports:
          - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"          
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port", "8080",
          "--ssl_port", "443",
          "--backend", "127.0.0.1:8081",
          "--service", "greeting-api.endpoints.lacapitalepilotage.cloud.goog",
          "--service_account_key", "/etc/nginx/creds/service-account-creds.json",
          "--version", "2017-12-03r1",
          "-n", "/etc/nginx/custom/nginx.conf"
        ]
        ports:
          - containerPort: 8080
          - containerPort: 443
        volumeMounts:
          - mountPath: /etc/nginx/custom
            name: nginx-config
            readOnly: true
          - mountPath: /etc/nginx/ssl
            name: nginx-ssl
            readOnly: true
          - mountPath: /etc/nginx/creds
            name: service-account-creds
            readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8090
          initialDelaySeconds: 25
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8090
          initialDelaySeconds: 25
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"          
          
          